### ISSUE TITLE
Fix project license

### ISSUE THREAD

**Issue by amitkrxyz** [flathub/com.usebruno.Bruno#1]
Bruno's repository is licensed under the MIT License, yet the Flathub page erroneously indicates that it is proprietary. I was confused for a while upon encountering this.

**Comment by starsep** [comment]
@helloanoop 
Currently https://flathub.org/apps/com.usebruno.Bruno looks like that :fearful: 
![image](https://github.com/flathub/com.usebruno.Bruno/assets/2798728/a014a5fa-fd85-497a-afdd-b4cf30e4d0d0)

Could you change the license here to MIT?
Unless it's not an error and you intend to add paid closed-source features to Flatpak release.

**Comment by regunakyle** [comment]
Bruno is still listed as proprietary in Flathub :thinking:
![Screenshot_20240213_214741](https://github.com/flathub/com.usebruno.Bruno/assets/60984878/3b47e727-d7e2-4115-b37e-143a23d1f696)

Is the fix not yet pushed to Flathub?

**Comment by ThatOneCalculator** [comment]
> Perhaps marking it as opensource and adding that some part of code is closed might be a middle ground.

You'd need to distribute two separate binaries, otherwise it would all be considered proprietary.

**Comment by helloanoop** [comment]
> You'd need to distribute two separate binaries, otherwise it would all be considered proprietary.

Thank you for clarifying @ThatOneCalculator !

**Comment by Abdull** [comment]
Flatpak / Flathub project license documentation and requirements:
* https://docs.flathub.org/docs/for-app-authors/requirements/#license
* https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_license
* https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-expressions/


@helloanoop , https://github.com/flathub/com.usebruno.Bruno/blob/5054bf69efa358a3a00530324f9c39e90ee8d543/com.usebruno.Bruno.metainfo.xml#L12C20-L12C35

![image](https://github.com/flathub/com.usebruno.Bruno/assets/529862/22a5f6eb-3319-41e4-b6d8-e596385ca0fb)


Notice the minus character at the end of `LicenseRef-MIT-`. This looks like a mistake to me. Maybe that is the reason why [Bruno's Flathub page](https://flathub.org/apps/com.usebruno.Bruno) still shows "Proprietary" as its license.

Maybe just change it to `LicenseRef-MIT` or just `MIT` ... compare to some randomly chosen other Flathub-hosted Flatpak app which uses `MIT`: https://github.com/flathub/org.firo.firo-qt/blob/014b5f51cb6c75e31b4e32de361c256af551b1e2/org.firo.firo-qt.metainfo.xml#L6 ( https://flathub.org/apps/org.firo.firo-qt )

**Comment by AligningEntropy** [comment]
(copying my comment from the #16 to be here in the related issue) 
This appears to have been reverted in Release 1.18.0 #22 and is back to showing the proprietary license badge.
If the goal is to have a dual license as the flatpak description
> Majority of our features are free and have been opensourced under the MIT license

AND [this commit](https://github.com/flathub/com.usebruno.Bruno/pull/22/commits/ad80123a7b39439b64651a92da14908ed8d07e16) indicate.

Then this license should utilize the [expression operators](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#license) such as [AND](https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-expressions/#d43-conjunctive-and-operator). This would result in the license being something like `<project_license>MIT AND LicenseRef-proprietary=https://usebruno.com/license</project_license>` (I could not find where the actual proprietary license was located to update the link to, so that would need adjustment once identified)

If not, then this change needs to be re-applied such that the license tag is once again `<project_license>MIT</project_license>`

**Comment by AligningEntropy** [comment]
I have created a PR [#27](https://github.com/flathub/com.usebruno.Bruno/pull/27) to address this regression.

**Comment by rugk** [comment]
https://github.com/flathub/com.usebruno.Bruno/blob/880392ee80fa4ad6b173ba4191c9959e16739013/com.usebruno.Bruno.metainfo.xml#L13 indeed still shows proprietary license, I also stumbled opon this and found this issue. So it is [MIT licensed](https://github.com/usebruno/bruno?tab=MIT-1-ov-file), at least, I guess, the source code that is used for this build?

Also see https://github.com/flathub/com.usebruno.Bruno/issues/28 where someone argues about it being dual-licensed, though.

**Comment by arrowmaster** [comment]
>So it is [MIT licensed](https://github.com/usebruno/bruno?tab=MIT-1-ov-file), at least, I guess, the source code that is used for this build?

The Flathub package does not build from source but instead downloads and extracts the AppImage on the end users system during install. AFAIK only the source code for the free features is MIT licensed, the prebuilt binary files that include features activated on payment are not MIT licensed.

https://github.com/flathub/com.usebruno.Bruno/blob/880392ee80fa4ad6b173ba4191c9959e16739013/com.usebruno.Bruno.yml#L35-L36

The only way to get this Flathub package labeled as MIT licensed would be to have it build from source and exclude the paid features.
